# This file MUST be at .github/workflows/cypress-demo.yml in your repo
name: Cypress Demo Runner
on:
  workflow_dispatch: # Ini wajib agar bisa dipicu via API

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: login.cy.js
          browser: chrome

      - name: Upload Video to Cloudinary
        if: always()
        run: |
          curl https://api.cloudinary.com/v1_1/${{ secrets.CLOUDINARY_CLOUD_NAME }}/video/upload \
            -X POST \
            -F "file=@cypress/videos/login.cy.js.mp4" \
            -F "upload_preset=${{ secrets.CLOUDINARY_UPLOAD_PRESET }}" \
            -F "public_id=latest_demo" \
            -F "resource_type=video" \
            -F "overwrite=true"

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos